### ISSUE TITLE
xonsh.sublime-syntax version upgrade

### ISSUE THREAD

**Issue by earwin** [eugenesvk/sublime-xonsh#1]
underlying Python.sublime-syntax was upgraded to version:2 at some point, so now xonsh.sublime-syntax fails to load

**Comment by earwin** [comment]
See https://github.com/eugenesvk/sublime-xonsh/blob/main/xonsh.sublime-syntax#L7

**Comment by earwin** [comment]
Now I've noticed you already have a branch implementing this.
Do you know any way to use it from within Package Control?

**Comment by eugenesvk** [comment]
I've also already submitted it to PC, you can track this PR for the package control status

https://github.com/wbond/package_control_channel/pull/8795

don't know how to use a specific tag manually, check PC docs or the easiest in the meantime would be to just copy the file to User folder and disable the package
